name: ab_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.1.0
  mason: "^0.1.0-dev.30"
  mason_logger: ^0.1.1
  path: ^1.8.0
  universal_io: ^2.0.4


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  ab:
